import { ThemeProvider } from '@/components/theme-provider';
import { NextIntlClientProvider, hasLocale } from 'next-intl';
import { notFound } from 'next/navigation';
import { routing } from '@/i18n/routing';
import './globals.css';
import Navbar from '@/components/Navbar';
import { Toaster } from '@/components/ui/sonner';
import ObserverProvider from './ObserverProvider';

export const metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default async function RootLayout({ children, params }) {
    const { locale } = await params;
    if (!hasLocale(routing.locales, locale)) {
        notFound();
    }

    return (
        <html lang={locale} suppressHydrationWarning>
            <body className="relative">
                <NextIntlClientProvider>
                    <ThemeProvider
                        attribute="class"
                        defaultTheme="system"
                        enableSystem
                        disableTransitionOnChang
                    >
                        <main className="w-full min-h-screen max-w-[1400px] mx-auto px-5 z-10">
                            {/* <div className="absolute inset-0 backdrop-blur-xs"></div> */}
                            <Navbar />
                            <ObserverProvider>{children}</ObserverProvider>
                            <Toaster />
                        </main>
                    </ThemeProvider>
                </NextIntlClientProvider>
            </body>
        </html>
    );
}
